### ISSUE TITLE
Building on M1 Mac

### ISSUE THREAD

**Issue by jordanrule** [google-research/dex-lang#1247]
Just wanted to leave a few notes on building the project on an M1 Mac (aarch64) should you decide to support the architecture in the future:
* The default download of Stack does not work, aarch64 requires `ghcup` to download a Stack that builds for the appropriate architecture (required for llvm-hs)
* The default install location of libpng (homebrew) is now `/opt/homebrew/include` so it requires an additional wildcard check in make
* Cryptonite does not build on `lts-18.23` for M1, (see [here](https://github.com/haskell-crypto/cryptonite/issues/372)) - I tried upgrading to a later version of GHC but I don't know enough about this project or Haskell build in general to fix the dependency chains

Just posting this in case it helps someone else or I missed something, as I would like to return to the project and look for possible contributions once it is working.

**Comment by dan-zheng** [comment]
Thanks for the issue! I got a new Apple M1 laptop recently, ran into all the build issues mentioned above.

After a day of debugging, I'm close to getting Dex to build on Apple M1:
- LLVM 15: `brew install llvm@15` and https://github.com/llvm-hs/llvm-hs/tree/llvm-15
- `resolver: lts-20.15` in `stack-macos.yaml`

Current status: upgrading to GHC 9.2.7 has resulted in some dex-lang compilation errors, probably due to language changes:

<details>

```
$ make
stack --stack-yaml=stack-macos.yaml build --ghc-options="-j +RTS -A256m -n2m -RTS" --extra-include-dirs=/opt/homebrew/include --extra-lib-dirs=/opt/homebrew/lib --fast
...
/Users/danielzheng/dex-lang/src/lib/Name.hs:1302:44: error:
    Bang pattern in expression context: !v
    Did you mean to add a space after the '!'?
     |
1302 |   lookupZipSubstFst v = ZipSubstReaderT $ (!v) <$> fst <$> ask
     |                                            ^^

/Users/danielzheng/dex-lang/src/lib/Name.hs:1303:44: error:
    Bang pattern in expression context: !v
    Did you mean to add a space after the '!'?
     |
1303 |   lookupZipSubstSnd v = ZipSubstReaderT $ (!v) <$> snd <$> ask
     |                                            ^^
```

</details>

I'll plan to follow-up here within a week. If the final fixes aren't too tricky, I should be able to share a pull request with instructions.

**Comment by dan-zheng** [comment]
In-progress fix at https://github.com/google-research/dex-lang/pull/1264. Dex builds on Apple M1 and simple examples run!

Requires LLVM 15: `brew install llvm@15`. Tests aren't all passing yet, working on fixing them next.
